name: Build and Continuous Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Build binaries for Linux and FreeBSD
      run: |
        go mod init github.com/probonopd/continuous-release-manager
        go get github.com/google/go-github/github
        go get golang.org/x/oauth2
        go build -ldflags="-s -w" -o continuous-release-manager-linux
        GOOS=freebsd go build -ldflags="-s -w" -o continuous-release-manager-freebsd

    - name: Create "continuous" release
      run: ./continuous-release-manager-linux
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload binaries to release
      run: |
        wget -cq https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz
        tar xvfz ghr_*.tar.gz
        ./ghr_*/ghr --username "$GITHUB_ACTOR" --token "$GITHUB_TOKEN" --replace --debug continuous ./continuous-release-manager-linux ./continuous-release-manager-freebsd
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
