name: Build and Continuous Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Build binary
      run: |
           go mod init github.com/probonopd/continuous-release-manager
           go build -o continuous-release-manager

    - name: Create "continuous" release
      run: ./continuous-release-manager
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload binary to release
      run: |
        gh release upload continuous ./continuous-release-manager
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
