name: Build and Continuous Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.16']
        arch: ['386', 'amd64', 'arm', 'arm64']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build binary
      run: |
        go mod init github.com/probonopd/continuous-release-manager
        go get github.com/google/go-github/github
        go get golang.org/x/oauth2
        GOARCH=${{ matrix.arch }} go build -o continuous-release-manager-${{ matrix.arch }}

    - name: Create "continuous" release
      run: ./continuous-release-manager
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload binary to release
      run: |
        gh release upload continuous ./continuous-release-manager-${{ matrix.arch }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
