name: Build and Continuous Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Build binaries for Linux and FreeBSD
      run: |
        go mod init github.com/probonopd/continuous-release-manager
        go get github.com/google/go-github/github
        go get golang.org/x/oauth2
        go build -ldflags="-s -w" -o continuous-release-manager-linux
        GOOS=freebsd go build -ldflags="-s -w" -o continuous-release-manager-freebsd

    - name: Create "continuous" release
      if: github.event_name == 'push'  # Only run for push events, not pull requests
      run: |
            RELEASE_ID=$(./continuous-release-manager-linux)
            echo "RELEASE_ID=${RELEASE_ID}" >> $GITHUB_ENV

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload binaries to release
      if: github.event_name == 'push'  # Only run for push events, not pull requests
      uses: xresloader/upload-to-github-release@v1.3.12
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "continuous-release-manager-*"
        draft: false
        verbose: true
        branches: main
        tag_name: continuous
        release_id: ${{ env.RELEASE_ID }}
